// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:leelame/features/auth/data/models/user_hive_model.dart';
import 'package:leelame/features/bid/data/models/bid_hive_model.dart';
import 'package:leelame/features/buyer/data/models/buyer_hive_model.dart';
import 'package:leelame/features/category/data/models/category_hive_model.dart';
import 'package:leelame/features/product/data/models/product_hive_model.dart';
import 'package:leelame/features/product_condition/data/models/product_condition_hive_model.dart';
import 'package:leelame/features/seller/data/models/seller_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BidHiveModelAdapter());
    registerAdapter(BuyerHiveModelAdapter());
    registerAdapter(CategoryHiveModelAdapter());
    registerAdapter(ProductConditionHiveModelAdapter());
    registerAdapter(ProductHiveModelAdapter());
    registerAdapter(SellerHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BidHiveModelAdapter());
    registerAdapter(BuyerHiveModelAdapter());
    registerAdapter(CategoryHiveModelAdapter());
    registerAdapter(ProductConditionHiveModelAdapter());
    registerAdapter(ProductHiveModelAdapter());
    registerAdapter(SellerHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
  }
}
